services:
  api_vanhungthinh:
    image: ${DOCKER_REGISTRY-}apivanhungthinh
    build:
      context: .
      dockerfile: API_VanThinhPhat/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    environment:
      MONGODB_URI: "" 
